#pragma once

#include "thc/thc_wrap.h"

typedef struct ChessBoard ChessBoard;

typedef thc_square ChessSquare;
typedef thc_move ChessMove;

typedef thc_movelist ChessMoveList;

typedef thc_game_ends ChessGameEnds;

// initialize a chess board
ChessBoard *chess_board_init();

// destroy a board created using board_init
void chess_board_destroy(ChessBoard *);

// generate a list of legal moves
// each move contains a src tile and a dst tile
void chess_board_gen_movelist(const ChessBoard *, ChessMoveList *);

// make a move
// the move should generated by board_gen_legal_movelist
void chess_board_move(const ChessBoard *, ChessMove);

bool chess_board_white_to_play(const ChessBoard *);

// get a string describing the board
// it uses the standard chars for pieces,
// and spaces for empty tiles
const char *chess_board_get_squares(const ChessBoard *);

ChessGameEnds chess_board_get_game_end(const ChessBoard *);
